- name: discussion on datatypes
  hosts: localhost
  connection: localhost
  vars:
    course: "devops with AIOPS"
    duration_in_hrs: 150
    is_live_session: true
    topics:
      - linux
      - ansible
      - shell
    more_detials:
      months: 5
      trainer: "Sivakuma reddy"
  tasks:
    - name: print information
      debug:
        msg: |
          name: {{ course }}
          duration: {{ duration_in_hrs }}
          is_live_session: {{ is_live_session }}
          topics: {{ topics }}
          more_details: {{ more_details }}