- name: demo on conditions
  hosts: localhost
  connection: localhost
  tasks:
    - name: print names
      debug:
        msg: "Hi {{ item }}"
      loop:
        - ramesh
        - raheem
        - sujitha