- name: demo on vars
  hosts: localhost
  connection: localhost
  vars:
    course: "ansible"
    trainer: "sivakumar"
    duration: "150hrs"
  tasks:
    - name: print the information
      vars: 
        course: "i am learning the devops"
      debug:
        msg: "I am learning {{ course }}, trainer is {{ trainer }}, and duration is {{ duration }}"